language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*@dev
  - SYMFONY_VERSION=dev-master

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - mkdir -p build/logs
  - composer require --prefer-source --no-interaction "symfony/symfony:${SYMFONY_VERSION}"
  - composer require --dev "satooshi/php-coveralls:dev-master"

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $COMPOSER_CACHE_DIR
